#!/usr/bin/env bash
set -euo pipefail

usage() {
	cat <<EOF
Usage: $0 [--name NAME] [--control-planes NAMES|COUNT] [--workers NAMES|COUNT]

	--name NAME                 Cluster name (default: kind)
	--control-planes VAL        Comma-separated node names or a number (default: 1)
	--workers VAL               Comma-separated node names or a number (default: 0)
	--image IMAGE               Node image (default: kindest/node:v1.34.0)

Examples:
	$0 --name my-cluster --control-planes 3 --workers worker1,worker2
	$0 --control-planes cp1,cp2 --workers 2
EOF
}

CLUSTER_NAME="kind"
CP_VAL="1"
WORKER_VAL="0"
IMAGE="kindest/node:v1.34.0"

while [[ $# -gt 0 ]]; do
	case "$1" in
		--name)
			CLUSTER_NAME="$2"; shift 2;;
		--control-planes)
			CP_VAL="$2"; shift 2;;
		--workers)
			WORKER_VAL="$2"; shift 2;;
		--image)
			IMAGE="$2"; shift 2;;
		-h|--help)
			usage; exit 0;;
		*)
			echo "Unknown arg: $1" >&2; usage; exit 2;;
	esac
done

split_or_generate() {
	local val="$1"; local prefix="$2"; local out_var="$3"
	if [[ "$val" =~ ^[0-9]+$ ]]; then
		local n="$val"
		local arr=()
		for i in $(seq 1 "$n"); do arr+=("${prefix}${i}"); done
	else
		IFS=',' read -r -a arr <<< "$val"
	fi
	eval "$out_var=(\"${arr[@]}\")"
}

split_or_generate "$CP_VAL" "cp-" cp_nodes
split_or_generate "$WORKER_VAL" "worker-" worker_nodes

TMP_CONFIG="$(mktemp --suffix=-kind-config.yaml)"
cat > "$TMP_CONFIG" <<EOF
# generated by installation.sh
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
EOF

first_cp=true
for name in "${cp_nodes[@]}"; do
	if [ "$first_cp" = true ]; then
		cat >> "$TMP_CONFIG" <<YAML
- role: control-plane
	name: ${CLUSTER_NAME}-${name}
	extraPortMappings:
		- containerPort: 80
			hostPort: 80
		- containerPort: 443
			hostPort: 443
	image: ${IMAGE}
YAML
		first_cp=false
	else
		cat >> "$TMP_CONFIG" <<YAML
- role: control-plane
	name: ${CLUSTER_NAME}-${name}
	image: ${IMAGE}
YAML
	fi
done

for name in "${worker_nodes[@]}"; do
	cat >> "$TMP_CONFIG" <<YAML
- role: worker
	name: ${CLUSTER_NAME}-${name}
	image: ${IMAGE}
YAML
done

echo "Using kind config: $TMP_CONFIG"
cat "$TMP_CONFIG"

kind create cluster --name "$CLUSTER_NAME" --config "$TMP_CONFIG"

kubectl get nodes --context "kind-${CLUSTER_NAME}"

echo "Cluster '$CLUSTER_NAME' created. Temporary config kept at: $TMP_CONFIG"
