apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: robot-shop
spec:
  ingressClassName: nginx
  rules:
    - host: robot-shop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
